CREATE TABLE IF NOT EXISTS CLIENT(ID IDENTITY PRIMARY KEY, NAME VARCHAR(200) NOT NULL,
    CONSTRAINT CHECK_CLIENT CHECK(LENGTH (NAME)>2));

CREATE TABLE IF NOT EXISTS PLANET(ID VARCHAR(200) NOT NULL PRIMARY KEY CHECK (ID = UPPER(id)),
    NAME VARCHAR(60) NOT NULL CONSTRAINT CHECK_PLANET CHECK(LENGTH (NAME)>1));

CREATE TABLE IF NOT EXISTS TICKET(ID IDENTITY PRIMARY KEY,
CREATED_AT TIMESTAMP NOT NULL,
CLIENT_ID BIGINT NOT NULL,
FROM_PLANET_ID VARCHAR(200) NOT NULL,
TO_PLANET_ID VARCHAR(200) NOT NULL,
FOREIGN KEY(CLIENT_ID) REFERENCES CLIENT(ID),
FOREIGN KEY(FROM_PLANET_ID) REFERENCES PLANET(ID),
FOREIGN KEY(TO_PLANET_ID) REFERENCES PLANET(ID));